[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
atom_id = "rnc2fycemiEgj4YbMSuwKFpdV6nkJonojCXib3j2by6"

[programs.mainnet]
atom_id = "rnc2fycemiEgj4YbMSuwKFpdV6nkJonojCXib3j2by6"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
