[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
atom_id = "2L71ccPAUz8NtKtHMUZtaopoS3CTnJSgaxatfHoGDvwM"

[programs.mainnet]
atom_id = "2L71ccPAUz8NtKtHMUZtaopoS3CTnJSgaxatfHoGDvwM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
